/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/auth/authenticate`; params?: Router.UnknownInputParams; } | { pathname: `/auth/choose`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownInputParams; } | { pathname: `/book/story`; params?: Router.UnknownInputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } } | { pathname: `/audio/[audio]`, params: Router.UnknownInputParams & { audio: string | number; } } | { pathname: `/authorsprofile/[author]`, params: Router.UnknownInputParams & { author: string | number; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownInputParams & { synopsis: string | number; } } | { pathname: `/usersprofile/[user]`, params: Router.UnknownInputParams & { user: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/clubs` | `/clubs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/authenticate`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/choose`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownOutputParams; } | { pathname: `/book/story`; params?: Router.UnknownOutputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownOutputParams & { unmatched: string[]; } } | { pathname: `/audio/[audio]`, params: Router.UnknownOutputParams & { audio: string; } } | { pathname: `/authorsprofile/[author]`, params: Router.UnknownOutputParams & { author: string; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownOutputParams & { synopsis: string; } } | { pathname: `/usersprofile/[user]`, params: Router.UnknownOutputParams & { user: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/clubs${`?${string}` | `#${string}` | ''}` | `/clubs${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/auth/authenticate${`?${string}` | `#${string}` | ''}` | `/auth/choose${`?${string}` | `#${string}` | ''}` | `/auth/onboard${`?${string}` | `#${string}` | ''}` | `/book/story${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/auth/authenticate`; params?: Router.UnknownInputParams; } | { pathname: `/auth/choose`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownInputParams; } | { pathname: `/book/story`; params?: Router.UnknownInputParams; } | `/${string}${`?${string}` | `#${string}` | ''}` | `/audio/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/authorsprofile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/book/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/usersprofile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } } | { pathname: `/audio/[audio]`, params: Router.UnknownInputParams & { audio: string | number; } } | { pathname: `/authorsprofile/[author]`, params: Router.UnknownInputParams & { author: string | number; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownInputParams & { synopsis: string | number; } } | { pathname: `/usersprofile/[user]`, params: Router.UnknownInputParams & { user: string | number; } };
    }
  }
}
