/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/book/story`; params?: Router.UnknownInputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownInputParams & { synopsis: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/book/story`; params?: Router.UnknownOutputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownOutputParams & { unmatched: string[]; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownOutputParams & { synopsis: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/auth/onboard${`?${string}` | `#${string}` | ''}` | `/auth/signin${`?${string}` | `#${string}` | ''}` | `/book/story${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/book/story`; params?: Router.UnknownInputParams; } | `/${string}` | `/book/${Router.SingleRoutePart<T>}` | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } } | { pathname: `/book/[synopsis]`, params: Router.UnknownInputParams & { synopsis: string | number; } };
    }
  }
}
